//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChimLib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChimLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;img src=&quot;&quot; alt=&quot;X&quot; /&gt;
        ///&lt;p&gt;Hi $$USER$$,&lt;/p&gt;
        ///&lt;p&gt;Your order #&lt;b&gt;$$ORDER$$&lt;/b&gt; has been successfully placed, here is a receipt for your purchase.&lt;/p&gt;
        ///&lt;p&gt;$$ADDRESS$$&lt;/p&gt;
        ///&lt;table&gt;
        ///    &lt;tr&gt;
        ///        &lt;th&gt;Product&lt;/th&gt;
        ///        &lt;th&gt;Color&lt;/th&gt;
        ///        &lt;th&gt;Size&lt;/th&gt;
        ///        &lt;th&gt;Unit Price&lt;/th&gt;
        ///        &lt;th&gt;Quantity&lt;/th&gt;
        ///        &lt;th&gt;Total&lt;/th&gt;
        ///    &lt;/tr&gt;
        ///    $$ITEMROWS$$
        ///&lt;/table&gt;
        ///&lt;table&gt;
        ///    &lt;tr&gt;
        ///        &lt;td&gt;Subtotal:&lt;/td&gt;
        ///        &lt;td&gt;$$SUBTOTAL$$&lt;/td&gt;
        ///    &lt;/tr&gt;
        ///    &lt;tr&gt;
        ///        &lt;td&gt;S&amp;H:&lt;/td&gt;
        ///        &lt;t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OrderConfirmation {
            get {
                return ResourceManager.GetString("OrderConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;img src=&quot;&quot; alt=&quot;X&quot; /&gt;
        ///&lt;p&gt;Hi $$USER$$,&lt;/p&gt;
        ///&lt;p&gt;Your order #&lt;b&gt;$$ORDER$$&lt;/b&gt; has just shipped. If you want to follow its progress, here are those shipping details.&lt;/p&gt;
        ///&lt;table&gt;
        ///    &lt;tr&gt;
        ///        &lt;th&gt;Shipping Service&lt;/th&gt;
        ///        &lt;th&gt;Tracking Number&lt;/th&gt;
        ///        &lt;th&gt;Shipping Date&lt;/th&gt;
        ///    &lt;/tr&gt;
        ///    $$ITEMROWS$$
        ///&lt;/table&gt;
        ///&lt;p&gt;This message is auto generated, for concern of your own frustration please do not reply to this e-mail. If you have any questions concerning your order, any issues or a dire need to [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StatusUpdate {
            get {
                return ResourceManager.GetString("StatusUpdate", resourceCulture);
            }
        }
    }
}
